In [410]:
import pandas as pd
import numpy as np
import json
import yaml
import xml

In [411]:
lpp_logic=pd.read_excel("LPP logic Table..xlsx")

In [412]:
lpp_logic

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,NaN,NaN,LPP Calculations,NaN
1,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN
4,NaN,Sub_category,Hp,Dell
5,NaN,1. Laptop,0.034,0.078
6,NaN,2. Monitor,0.012,0.056
7,NaN,3. Toner,0.091,0.023
8,NaN,4. Laserjet,0.065,0.035
9,NaN,5. Inkjet,0.012,0.056
10,NaN,6. Desktop,0.091,0.023
11,NaN,7. Ink,0.065,0.035
12,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN
15,NaN,Reduce Map by the given % to create LPP,NaN,NaN

In [413]:
lpp_logic["Sub_category"]=lpp_logic["Unnamed: 1"]
lpp_logic["Hp"]=lpp_logic["Unnamed: 2"]
lpp_logic["Dell"]=lpp_logic["Unnamed: 3"]

In [414]:
lpp_logic=lpp_logic.drop(["Unnamed: 0"],axis=1)

In [415]:
lpp=(pd.DataFrame(data=(lpp_logic[5:12]),columns=["Sub_category","Hp","Dell"])).reset_index(drop=True)

In [416]:
lpp

  Sub_category     Hp   Dell
0    1. Laptop  0.034  0.078
1   2. Monitor  0.012  0.056
2     3. Toner  0.091  0.023
3  4. Laserjet  0.065  0.035
4    5. Inkjet  0.012  0.056
5   6. Desktop  0.091  0.023
6       7. Ink  0.065  0.035

In [417]:
promo=pd.read_excel("Promotion Table.xlsx",skiprows=[0,1,2,3,4],header=1)
promo=promo.drop(['Unnamed: 0'],axis=1)
promo=promo.drop([3,4,5,6,7],axis=0)
promo=promo.reset_index(drop=True)

In [418]:
promo

,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct)
0,Supply,10% off ink,Buy 2 get 1 free,5% off toner,20% off paper
1,Print Hardware,15% off printers,Free setup service,2% off scanners,$10 off printers
2,PC,£5 off laptops,Free accessories,Free accessories,15 % off
3,G0L15B,NaN,NaN,NaN,NaN
4,7Y4T6QB,NaN,NaN,NaN,NaN
...,...,...,...,...,...
98,7KW56A,NaN,NaN,NaN,NaN
99,X2214B,NaN,NaN,NaN,NaN
100,8F8Z3PA,NaN,NaN,NaN,NaN
101,77S54PA,NaN,NaN,NaN,NaN
102,B3P21A,NaN,NaN,NaN,NaN

In [419]:
sellermap=pd.read_excel("Seller Mapping Table.xlsx")

In [420]:
sellermap

                   Sellers_name           homologated_sellers
0                Cocoblu Retail           BJ's Wholesale Club
1      RK World Infocom Pvt Ltd                American Eagle
2    Appario Retail Private Ltd                      Tapestry
3              RetailEZ Pvt Ltd           Wakefern / ShopRite
4                 ETrade Online          Harbor Freight Tools
..                          ...                           ...
898            Hydroshell India  Barnes and Noble Booksellers
899                 KT FASHIONS           J.C. Penney Company
900               Shoplite 0000                      Tapestry
901                 Bestbuybook        Sprouts Farmers Market
902                  Seetabooks                  Advance Auto

[903 rows x 2 columns]

In [421]:
sku=pd.read_xml("SKU Table.xml")

In [422]:
sku

              PN      Sku
0        Pib01a1  0X749QB
1        Pib01a2  75X62BB
2        Pib01a3   DF627B
3        Pib01a4   4ZB96A
4        Pib01a5  0R0N0QB
...          ...      ...
1593  Pib01a1594  4KB93BB
1594  Pib01a1595   X2231B
1595  Pib01a1596   B3P21A
1596  Pib01a1597  78X20QB
1597  Pib01a1598   CF364A

[1598 rows x 2 columns]

In [423]:
with open("Price List Table.yaml") as y:
    price=yaml.safe_load(y)

In [424]:
price=pd.DataFrame(price)

In [425]:
price

         MAP                 PL      sku
0     106684   DELL0X_PC_Laptop  0X749QB
1      35611  DELL75_PC_Monitor  75X62BB
2      29914     DELLDF_SUP_TON   DF627B
3      39258         HP4Z_PH_LJ   4ZB96A
4     139670   DELL0R_PC_Laptop  0R0N0QB
...      ...                ...      ...
1593    3565     DELL4K_SUP_INK  4KB93BB
1594    6716     DELLX2_SUP_TON   X2231B
1595    6868       HPB3_SUP_INK   B3P21A
1596   47937  DELL78_PC_Desktop  78X20QB
1597   28243       HPCF_SUP_TON   CF364A

[1598 rows x 3 columns]

In [426]:
df1 = pd.read_json("Category Mapping Table.json",lines=True)

In [427]:
df1

                     PL      sku
0      DELL0X_PC_Laptop  0X749QB
1     DELL75_PC_Monitor  75X62BB
2        DELLDF_SUP_TON   DF627B
3            HP4Z_PH_LJ   4ZB96A
4      DELL0R_PC_Laptop  0R0N0QB
...                 ...      ...
1593     DELL4K_SUP_INK  4KB93BB
1594     DELLX2_SUP_TON   X2231B
1595       HPB3_SUP_INK   B3P21A
1596  DELL78_PC_Desktop  78X20QB
1597       HPCF_SUP_TON   CF364A

[1598 rows x 2 columns]

In [428]:
dp=pd.DataFrame(promo.iloc[3:,0:1]).reset_index(drop=True)
dp['sku']=dp['Category']
dp1=pd.merge(dp,df1,on='sku',how='left')
#Category=dp1['PL']
dp2=pd.merge(promo,dp1,on='Category',how='left').drop(['sku'],axis=1)

In [429]:
dp2

,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),PL
0,Supply,10% off ink,Buy 2 get 1 free,5% off toner,20% off paper,NaN
1,Print Hardware,15% off printers,Free setup service,2% off scanners,$10 off printers,NaN
2,PC,£5 off laptops,Free accessories,Free accessories,15 % off,NaN
3,G0L15B,NaN,NaN,NaN,NaN,DELLG0_SUP_INK
4,7Y4T6QB,NaN,NaN,NaN,NaN,DELL7Y_PC_Desktop
...,...,...,...,...,...,...
98,7KW56A,NaN,NaN,NaN,NaN,HP7K_PH_LJ
99,X2214B,NaN,NaN,NaN,NaN,DELLX2_SUP_TON
100,8F8Z3PA,NaN,NaN,NaN,NaN,HP8F_PC_Laptop
101,77S54PA,NaN,NaN,NaN,NaN,HP77_PC_Laptop
102,B3P21A,NaN,NaN,NaN,NaN,HPB3_SUP_INK

In [430]:
df2=pd.read_json("PL Table.json",lines=True)

In [431]:
df2

          sku                 PL
0     0X749QB   DELL0X_PC_Laptop
1     75X62BB  DELL75_PC_Monitor
2      DF627B     DELLDF_SUP_TON
3      4ZB96A         HP4Z_PH_LJ
4     0R0N0QB   DELL0R_PC_Laptop
...       ...                ...
1593  4KB93BB     DELL4K_SUP_INK
1594   X2231B     DELLX2_SUP_TON
1595   B3P21A       HPB3_SUP_INK
1596  78X20QB  DELL78_PC_Desktop
1597   CF364A       HPCF_SUP_TON

[1598 rows x 2 columns]

In [432]:
df2[['Brand','Sub','Item']]=df2['PL'].str.split('_',n=2,expand=True)

In [433]:
df2

          sku                 PL   Brand  Sub     Item
0     0X749QB   DELL0X_PC_Laptop  DELL0X   PC   Laptop
1     75X62BB  DELL75_PC_Monitor  DELL75   PC  Monitor
2      DF627B     DELLDF_SUP_TON  DELLDF  SUP      TON
3      4ZB96A         HP4Z_PH_LJ    HP4Z   PH       LJ
4     0R0N0QB   DELL0R_PC_Laptop  DELL0R   PC   Laptop
...       ...                ...     ...  ...      ...
1593  4KB93BB     DELL4K_SUP_INK  DELL4K  SUP      INK
1594   X2231B     DELLX2_SUP_TON  DELLX2  SUP      TON
1595   B3P21A       HPB3_SUP_INK    HPB3  SUP      INK
1596  78X20QB  DELL78_PC_Desktop  DELL78   PC  Desktop
1597   CF364A       HPCF_SUP_TON    HPCF  SUP      TON

[1598 rows x 5 columns]

In [434]:
sdf=df2.sort_values(by=['Item','Brand'], ascending=True)

In [435]:
sdf

          sku                 PL   Brand  Sub     Item
336   03A32QB  DELL03_PC_Desktop  DELL03   PC  Desktop
1067  088Q1QB  DELL08_PC_Desktop  DELL08   PC  Desktop
231   094O7QB  DELL09_PC_Desktop  DELL09   PC  Desktop
592   0R043QB  DELL0R_PC_Desktop  DELL0R   PC  Desktop
810   0S5O0QB  DELL0S_PC_Desktop  DELL0S   PC  Desktop
...       ...                ...     ...  ...      ...
1017  L0S00AA       HPL0_SUP_UNK    HPL0  SUP      UNK
1191  L0S03AA       HPL0_SUP_UNK    HPL0  SUP      UNK
1337  L0S09AA       HPL0_SUP_UNK    HPL0  SUP      UNK
1350  L0R97AA       HPL0_SUP_UNK    HPL0  SUP      UNK
1454  L0R94AA       HPL0_SUP_UNK    HPL0  SUP      UNK

[1598 rows x 5 columns]

In [436]:
sdf1=pd.DataFrame(sdf,columns=["sku","PL","Brand","Item","Sub","lp"])

In [437]:
sdf['Item'].unique()

array(['Desktop', 'IJ', 'INK', 'LJ', 'Laptop', 'Monitor', 'SJ', 'TON',
       'UNK'], dtype=object)

In [438]:
sdf['Item'].value_counts()

Item
INK        426
Laptop     416
TON        326
Desktop    164
IJ          84
LJ          74
Monitor     60
UNK         28
SJ          20
Name: count, dtype: int64

In [439]:
il=sdf1['Item'].unique().tolist()

In [440]:
lpp

  Sub_category     Hp   Dell
0    1. Laptop  0.034  0.078
1   2. Monitor  0.012  0.056
2     3. Toner  0.091  0.023
3  4. Laserjet  0.065  0.035
4    5. Inkjet  0.012  0.056
5   6. Desktop  0.091  0.023
6       7. Ink  0.065  0.035

In [441]:
sdf1['lp'].unique()

array([nan])

In [442]:
sdf1['Item'].unique()

array(['Desktop', 'IJ', 'INK', 'LJ', 'Laptop', 'Monitor', 'SJ', 'TON',
       'UNK'], dtype=object)

In [443]:
sdf1

          sku                 PL   Brand     Item  Sub  lp
336   03A32QB  DELL03_PC_Desktop  DELL03  Desktop   PC NaN
1067  088Q1QB  DELL08_PC_Desktop  DELL08  Desktop   PC NaN
231   094O7QB  DELL09_PC_Desktop  DELL09  Desktop   PC NaN
592   0R043QB  DELL0R_PC_Desktop  DELL0R  Desktop   PC NaN
810   0S5O0QB  DELL0S_PC_Desktop  DELL0S  Desktop   PC NaN
...       ...                ...     ...      ...  ...  ..
1017  L0S00AA       HPL0_SUP_UNK    HPL0      UNK  SUP NaN
1191  L0S03AA       HPL0_SUP_UNK    HPL0      UNK  SUP NaN
1337  L0S09AA       HPL0_SUP_UNK    HPL0      UNK  SUP NaN
1350  L0R97AA       HPL0_SUP_UNK    HPL0      UNK  SUP NaN
1454  L0R94AA       HPL0_SUP_UNK    HPL0      UNK  SUP NaN

[1598 rows x 6 columns]

In [444]:
sdf1['lp']=0

In [445]:
sdf1['lp'].unique()

array([0])

In [446]:
lpp

  Sub_category     Hp   Dell
0    1. Laptop  0.034  0.078
1   2. Monitor  0.012  0.056
2     3. Toner  0.091  0.023
3  4. Laserjet  0.065  0.035
4    5. Inkjet  0.012  0.056
5   6. Desktop  0.091  0.023
6       7. Ink  0.065  0.035

In [447]:
lpp['Sub_category']=lpp['Sub_category'].str.strip()    # remove spaces

In [448]:
lpp['Sub_category']=lpp['Sub_category'].str.slice(3)  #remove unwanrted start

In [449]:
new_row = [{'Sub_category': 'UNK', 'Hp': 0.065, 'Dell': 0.035},{'Sub_category': 'SJ', 'Hp': 0.065, 'Dell': 0.035}]
lpp=pd.concat([lpp, pd.DataFrame(new_row)], ignore_index=True)  #adding new row

In [450]:
lpp['Sub_category'] = lpp['Sub_category'].str.replace('Toner', 'TON')
lpp['Sub_category'] = lpp['Sub_category'].str.replace('Laserjet', 'LJ')
lpp['Sub_category'] = lpp['Sub_category'].str.replace('Inkjet', 'IJ')
lpp['Sub_category'] = lpp['Sub_category'].str.replace('Ink', 'INK')
#replace string values it should perform one by one

In [451]:
lpp

  Sub_category     Hp   Dell
0       Laptop  0.034  0.078
1      Monitor  0.012  0.056
2          TON  0.091  0.023
3           LJ  0.065  0.035
4           IJ  0.012  0.056
5      Desktop  0.091  0.023
6          INK  0.065  0.035
7          UNK  0.065  0.035
8           SJ  0.065  0.035

In [452]:
keys=lpp['Sub_category'].tolist()
values1=lpp['Hp'].tolist()
values2=lpp['Dell'].tolist()	
#list conversion

In [453]:
#converts list to dictionary using zip function
replacements1=dict(zip(keys, values1))
replacements2=dict(zip(keys, values2))

In [454]:
replacements1

{'Laptop': 0.034,
 'Monitor': 0.012,
 'TON': 0.091,
 'LJ': 0.065,
 'IJ': 0.012,
 'Desktop': 0.091,
 'INK': 0.065,
 'UNK': 0.065,
 'SJ': 0.065}

In [455]:
replacements =replacements1                           #filling the llp detection values to the dataframe

for item, value in replacements.items():
    sdf1.loc[
        (sdf1['Item'] == item) & 
        (sdf1['Brand'].str.contains('HP', na=False)), 
        'lp'
    ] = sdf1.loc[
        (sdf1['Item'] == item) & 
        (sdf1['Brand'].str.contains('HP', na=False)), 
        'lp'
    ].replace(0, value)

C:\Users\samsu\AppData\Local\Temp\ipykernel_13152\2274078791.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034 0.034
 0.034 0.034 0.034 0.034 0.034 0.034]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  sdf1.loc[

In [456]:
replacements = replacements2
for item, value in replacements.items():
    sdf1.loc[
        (sdf1['Item'] == item) & 
        (sdf1['Brand'].str.contains('DELL', na=False)), 
        'lp'
    ] = sdf1.loc[
        (sdf1['Item'] == item) & 
        (sdf1['Brand'].str.contains('DELL', na=False)), 
        'lp'
    ].replace(0, value)

In [457]:
sdf1

          sku                 PL   Brand     Item  Sub     lp
336   03A32QB  DELL03_PC_Desktop  DELL03  Desktop   PC  0.023
1067  088Q1QB  DELL08_PC_Desktop  DELL08  Desktop   PC  0.023
231   094O7QB  DELL09_PC_Desktop  DELL09  Desktop   PC  0.023
592   0R043QB  DELL0R_PC_Desktop  DELL0R  Desktop   PC  0.023
810   0S5O0QB  DELL0S_PC_Desktop  DELL0S  Desktop   PC  0.023
...       ...                ...     ...      ...  ...    ...
1017  L0S00AA       HPL0_SUP_UNK    HPL0      UNK  SUP  0.065
1191  L0S03AA       HPL0_SUP_UNK    HPL0      UNK  SUP  0.065
1337  L0S09AA       HPL0_SUP_UNK    HPL0      UNK  SUP  0.065
1350  L0R97AA       HPL0_SUP_UNK    HPL0      UNK  SUP  0.065
1454  L0R94AA       HPL0_SUP_UNK    HPL0      UNK  SUP  0.065

[1598 rows x 6 columns]

In [458]:
sdf1['lp'].unique() #reference to check

array([0.023, 0.091, 0.056, 0.012, 0.035, 0.065, 0.078, 0.034])

In [459]:
df5=pd.merge(price,sdf1,on='sku',how='inner')

In [460]:
df5.duplicated().sum()

np.int64(0)

In [461]:
df5

,MAP,PL_x,sku,PL_y,Brand,Item,Sub,lp
0,106684,DELL0X_PC_Laptop,0X749QB,DELL0X_PC_Laptop,DELL0X,Laptop,PC,0.078
1,35611,DELL75_PC_Monitor,75X62BB,DELL75_PC_Monitor,DELL75,Monitor,PC,0.056
2,29914,DELLDF_SUP_TON,DF627B,DELLDF_SUP_TON,DELLDF,TON,SUP,0.023
3,39258,HP4Z_PH_LJ,4ZB96A,HP4Z_PH_LJ,HP4Z,LJ,PH,0.065
4,139670,DELL0R_PC_Laptop,0R0N0QB,DELL0R_PC_Laptop,DELL0R,Laptop,PC,0.078
...,...,...,...,...,...,...,...,...
1601,3565,DELL4K_SUP_INK,4KB93BB,DELL4K_SUP_INK,DELL4K,INK,SUP,0.035
1602,6716,DELLX2_SUP_TON,X2231B,DELLX2_SUP_TON,DELLX2,TON,SUP,0.023
1603,6868,HPB3_SUP_INK,B3P21A,HPB3_SUP_INK,HPB3,INK,SUP,0.065
1604,47937,DELL78_PC_Desktop,78X20QB,DELL78_PC_Desktop,DELL78,Desktop,PC,0.023
1605,28243,HPCF_SUP_TON,CF364A,HPCF_SUP_TON,HPCF,TON,SUP,0.091

In [462]:
df5['Lpp']=df5['MAP']*df5['lp']

In [463]:
df5

,MAP,PL_x,sku,PL_y,Brand,Item,Sub,lp,Lpp
0,106684,DELL0X_PC_Laptop,0X749QB,DELL0X_PC_Laptop,DELL0X,Laptop,PC,0.078,8321.352
1,35611,DELL75_PC_Monitor,75X62BB,DELL75_PC_Monitor,DELL75,Monitor,PC,0.056,1994.216
2,29914,DELLDF_SUP_TON,DF627B,DELLDF_SUP_TON,DELLDF,TON,SUP,0.023,688.022
3,39258,HP4Z_PH_LJ,4ZB96A,HP4Z_PH_LJ,HP4Z,LJ,PH,0.065,2551.770
4,139670,DELL0R_PC_Laptop,0R0N0QB,DELL0R_PC_Laptop,DELL0R,Laptop,PC,0.078,10894.260
...,...,...,...,...,...,...,...,...,...
1601,3565,DELL4K_SUP_INK,4KB93BB,DELL4K_SUP_INK,DELL4K,INK,SUP,0.035,124.775
1602,6716,DELLX2_SUP_TON,X2231B,DELLX2_SUP_TON,DELLX2,TON,SUP,0.023,154.468
1603,6868,HPB3_SUP_INK,B3P21A,HPB3_SUP_INK,HPB3,INK,SUP,0.065,446.420
1604,47937,DELL78_PC_Desktop,78X20QB,DELL78_PC_Desktop,DELL78,Desktop,PC,0.023,1102.551
1605,28243,HPCF_SUP_TON,CF364A,HPCF_SUP_TON,HPCF,TON,SUP,0.091,2570.113

In [464]:
df5['Lpp']=df5['MAP']-df5['Lpp']

In [465]:
df5['PL']=df5['PL_x']

In [466]:
df5.head(10)

,MAP,PL_x,sku,PL_y,Brand,Item,Sub,lp,Lpp,PL
0,106684,DELL0X_PC_Laptop,0X749QB,DELL0X_PC_Laptop,DELL0X,Laptop,PC,0.078,98362.648,DELL0X_PC_Laptop
1,35611,DELL75_PC_Monitor,75X62BB,DELL75_PC_Monitor,DELL75,Monitor,PC,0.056,33616.784,DELL75_PC_Monitor
2,29914,DELLDF_SUP_TON,DF627B,DELLDF_SUP_TON,DELLDF,TON,SUP,0.023,29225.978,DELLDF_SUP_TON
3,39258,HP4Z_PH_LJ,4ZB96A,HP4Z_PH_LJ,HP4Z,LJ,PH,0.065,36706.230,HP4Z_PH_LJ
4,139670,DELL0R_PC_Laptop,0R0N0QB,DELL0R_PC_Laptop,DELL0R,Laptop,PC,0.078,128775.740,DELL0R_PC_Laptop
5,993854,DELL7L_PH_IJ,7LE37B,DELL7L_PH_IJ,DELL7L,IJ,PH,0.056,938198.176,DELL7L_PH_IJ
6,49687,DELL89_PC_Desktop,89Z55QB,DELL89_PC_Desktop,DELL89,Desktop,PC,0.023,48544.199,DELL89_PC_Desktop
7,102079,HP8C_PC_Laptop,8C4R9PA,HP8C_PC_Laptop,HP8C,Laptop,PC,0.034,98608.314,HP8C_PC_Laptop
8,9900,DELLG0_SUP_INK,G0L15B,DELLG0_SUP_INK,DELLG0,INK,SUP,0.035,9553.500,DELLG0_SUP_INK
9,28788,DELLDF_SUP_TON,DF853B,DELLDF_SUP_TON,DELLDF,TON,SUP,0.023,28125.876,DELLDF_SUP_TON

In [467]:
finaldf=pd.DataFrame(df5,columns=[ 'PL','sku','Brand','Item','Sub','MAP','Lpp'])

In [468]:
finaldf.head(10)

                  PL      sku   Brand     Item  Sub     MAP         Lpp
0   DELL0X_PC_Laptop  0X749QB  DELL0X   Laptop   PC  106684   98362.648
1  DELL75_PC_Monitor  75X62BB  DELL75  Monitor   PC   35611   33616.784
2     DELLDF_SUP_TON   DF627B  DELLDF      TON  SUP   29914   29225.978
3         HP4Z_PH_LJ   4ZB96A    HP4Z       LJ   PH   39258   36706.230
4   DELL0R_PC_Laptop  0R0N0QB  DELL0R   Laptop   PC  139670  128775.740
5       DELL7L_PH_IJ   7LE37B  DELL7L       IJ   PH  993854  938198.176
6  DELL89_PC_Desktop  89Z55QB  DELL89  Desktop   PC   49687   48544.199
7     HP8C_PC_Laptop  8C4R9PA    HP8C   Laptop   PC  102079   98608.314
8     DELLG0_SUP_INK   G0L15B  DELLG0      INK  SUP    9900    9553.500
9     DELLDF_SUP_TON   DF853B  DELLDF      TON  SUP   28788   28125.876

In [469]:
########################

In [470]:
dp2

,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),PL
0,Supply,10% off ink,Buy 2 get 1 free,5% off toner,20% off paper,NaN
1,Print Hardware,15% off printers,Free setup service,2% off scanners,$10 off printers,NaN
2,PC,£5 off laptops,Free accessories,Free accessories,15 % off,NaN
3,G0L15B,NaN,NaN,NaN,NaN,DELLG0_SUP_INK
4,7Y4T6QB,NaN,NaN,NaN,NaN,DELL7Y_PC_Desktop
...,...,...,...,...,...,...
98,7KW56A,NaN,NaN,NaN,NaN,HP7K_PH_LJ
99,X2214B,NaN,NaN,NaN,NaN,DELLX2_SUP_TON
100,8F8Z3PA,NaN,NaN,NaN,NaN,HP8F_PC_Laptop
101,77S54PA,NaN,NaN,NaN,NaN,HP77_PC_Laptop
102,B3P21A,NaN,NaN,NaN,NaN,HPB3_SUP_INK

In [471]:
 joindf=dp2.merge(finaldf, on='PL',how='left').drop_duplicates(subset='Category')
 joindf

,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),PL,sku,Brand,Item,Sub,MAP,Lpp
0,Supply,10% off ink,Buy 2 get 1 free,5% off toner,20% off paper,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Print Hardware,15% off printers,Free setup service,2% off scanners,$10 off printers,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PC,£5 off laptops,Free accessories,Free accessories,15 % off,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,G0L15B,NaN,NaN,NaN,NaN,DELLG0_SUP_INK,G0L15B,DELLG0,INK,SUP,9900.0,9553.500
17,7Y4T6QB,NaN,NaN,NaN,NaN,DELL7Y_PC_Desktop,7Y4R5QB,DELL7Y,Desktop,PC,60473.0,59082.121
...,...,...,...,...,...,...,...,...,...,...,...,...
1356,7KW56A,NaN,NaN,NaN,NaN,HP7K_PH_LJ,7KW64A,HP7K,LJ,PH,45886.0,42903.410
1358,X2214B,NaN,NaN,NaN,NaN,DELLX2_SUP_TON,X2631B,DELLX2,TON,SUP,11147.0,10890.619
1374,8F8Z3PA,NaN,NaN,NaN,NaN,HP8F_PC_Laptop,8F6C9PA,HP8F,Laptop,PC,120699.0,116595.234
1393,77S54PA,NaN,NaN,NaN,NaN,HP77_PC_Laptop,77S54PA,HP77,Laptop,PC,77429.0,74796.414
1394,B3P21A,NaN,NaN,NaN,NaN,HPB3_SUP_INK,B3P20A,HPB3,INK,SUP,7158.0,6692.730

In [472]:
joindf

,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),PL,sku,Brand,Item,Sub,MAP,Lpp
0,Supply,10% off ink,Buy 2 get 1 free,5% off toner,20% off paper,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Print Hardware,15% off printers,Free setup service,2% off scanners,$10 off printers,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PC,£5 off laptops,Free accessories,Free accessories,15 % off,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,G0L15B,NaN,NaN,NaN,NaN,DELLG0_SUP_INK,G0L15B,DELLG0,INK,SUP,9900.0,9553.500
17,7Y4T6QB,NaN,NaN,NaN,NaN,DELL7Y_PC_Desktop,7Y4R5QB,DELL7Y,Desktop,PC,60473.0,59082.121
...,...,...,...,...,...,...,...,...,...,...,...,...
1356,7KW56A,NaN,NaN,NaN,NaN,HP7K_PH_LJ,7KW64A,HP7K,LJ,PH,45886.0,42903.410
1358,X2214B,NaN,NaN,NaN,NaN,DELLX2_SUP_TON,X2631B,DELLX2,TON,SUP,11147.0,10890.619
1374,8F8Z3PA,NaN,NaN,NaN,NaN,HP8F_PC_Laptop,8F6C9PA,HP8F,Laptop,PC,120699.0,116595.234
1393,77S54PA,NaN,NaN,NaN,NaN,HP77_PC_Laptop,77S54PA,HP77,Laptop,PC,77429.0,74796.414
1394,B3P21A,NaN,NaN,NaN,NaN,HPB3_SUP_INK,B3P20A,HPB3,INK,SUP,7158.0,6692.730

In [473]:
joindf.loc[3:, 'Q1 (Nov-Jan)'] = joindf['Q1 (Nov-Jan)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])
joindf.loc[3:, 'Q2 (Feb-Apr)'] = joindf['Q2 (Feb-Apr)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])
joindf.loc[3:, 'Q3 (May-Jul)'] = joindf['Q3 (May-Jul)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])
joindf.loc[3:, 'Q4 (Aug-Oct)'] = joindf['Q4 (Aug-Oct)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])

C:\Users\samsu\AppData\Local\Temp\ipykernel_13152\2773364986.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  joindf.loc[3:, 'Q1 (Nov-Jan)'] = joindf['Q1 (Nov-Jan)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])
C:\Users\samsu\AppData\Local\Temp\ipykernel_13152\2773364986.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  joindf.loc[3:, 'Q2 (Feb-Apr)'] = joindf['Q2 (Feb-Apr)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])
C:\Users\samsu\AppData\Local\Temp\ipykernel_13152\2773364986.py:3: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  joindf.loc[3:, 'Q3 (May-Jul)'] = joindf['Q3 (May-Jul)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])
C:\Users\samsu\AppData\Local\Temp\ipykernel_13152\2773364986.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  joindf.loc[3:, 'Q4 (Aug-Oct)'] = joindf['Q4 (Aug-Oct)'].iloc[3:].fillna(joindf['Lpp'].iloc[3:])

In [474]:
joindf

,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),PL,sku,Brand,Item,Sub,MAP,Lpp
0,Supply,10% off ink,Buy 2 get 1 free,5% off toner,20% off paper,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Print Hardware,15% off printers,Free setup service,2% off scanners,$10 off printers,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PC,£5 off laptops,Free accessories,Free accessories,15 % off,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,G0L15B,9553.5,9553.5,9553.5,9553.5,DELLG0_SUP_INK,G0L15B,DELLG0,INK,SUP,9900.0,9553.500
17,7Y4T6QB,59082.121,59082.121,59082.121,59082.121,DELL7Y_PC_Desktop,7Y4R5QB,DELL7Y,Desktop,PC,60473.0,59082.121
...,...,...,...,...,...,...,...,...,...,...,...,...
1356,7KW56A,42903.41,42903.41,42903.41,42903.41,HP7K_PH_LJ,7KW64A,HP7K,LJ,PH,45886.0,42903.410
1358,X2214B,10890.619,10890.619,10890.619,10890.619,DELLX2_SUP_TON,X2631B,DELLX2,TON,SUP,11147.0,10890.619
1374,8F8Z3PA,116595.234,116595.234,116595.234,116595.234,HP8F_PC_Laptop,8F6C9PA,HP8F,Laptop,PC,120699.0,116595.234
1393,77S54PA,74796.414,74796.414,74796.414,74796.414,HP77_PC_Laptop,77S54PA,HP77,Laptop,PC,77429.0,74796.414
1394,B3P21A,6692.73,6692.73,6692.73,6692.73,HPB3_SUP_INK,B3P20A,HPB3,INK,SUP,7158.0,6692.730

In [475]:
joindf.columns

Index(['Category', 'Q1 (Nov-Jan)', 'Q2 (Feb-Apr)', 'Q3 (May-Jul)',
       'Q4 (Aug-Oct)', 'PL', 'sku', 'Brand', 'Item', 'Sub', 'MAP', 'Lpp'],
      dtype='object')

In [476]:
jdf=joindf[['Category', 'Q1 (Nov-Jan)', 'Q2 (Feb-Apr)', 'Q3 (May-Jul)',
       'Q4 (Aug-Oct)', 'PL', 'Brand', 'Item', 'Sub',
       ]]

In [477]:
jdf

,Category,Q1 (Nov-Jan),Q2 (Feb-Apr),Q3 (May-Jul),Q4 (Aug-Oct),PL,Brand,Item,Sub
0,Supply,10% off ink,Buy 2 get 1 free,5% off toner,20% off paper,NaN,NaN,NaN,NaN
1,Print Hardware,15% off printers,Free setup service,2% off scanners,$10 off printers,NaN,NaN,NaN,NaN
2,PC,£5 off laptops,Free accessories,Free accessories,15 % off,NaN,NaN,NaN,NaN
3,G0L15B,9553.5,9553.5,9553.5,9553.5,DELLG0_SUP_INK,DELLG0,INK,SUP
17,7Y4T6QB,59082.121,59082.121,59082.121,59082.121,DELL7Y_PC_Desktop,DELL7Y,Desktop,PC
...,...,...,...,...,...,...,...,...,...
1356,7KW56A,42903.41,42903.41,42903.41,42903.41,HP7K_PH_LJ,HP7K,LJ,PH
1358,X2214B,10890.619,10890.619,10890.619,10890.619,DELLX2_SUP_TON,DELLX2,TON,SUP
1374,8F8Z3PA,116595.234,116595.234,116595.234,116595.234,HP8F_PC_Laptop,HP8F,Laptop,PC
1393,77S54PA,74796.414,74796.414,74796.414,74796.414,HP77_PC_Laptop,HP77,Laptop,PC
1394,B3P21A,6692.73,6692.73,6692.73,6692.73,HPB3_SUP_INK,HPB3,INK,SUP

In [478]:
jdf1=jdf.iloc[3:].sort_values(by=['Item'])

In [479]:
jdf1['Item'].unique()

array(['Desktop', 'IJ', 'INK', 'LJ', 'Laptop', 'Monitor', 'SJ', 'TON',
       'UNK'], dtype=object)

In [480]:
jdf1['Q3 (May-Jul)'] = jdf1.apply(
    lambda row:0.5 * row['Q4 (Aug-Oct)'] if row['Item'] == 'TON' else 0,
    axis=1)

In [481]:
#jdf1['Q3 (May-Jul)'].loc[jdf1['Item']=='TON']=0.05 * jdf1['Q3 (May-Jul)']

In [482]:
fpromo=pd.DataFrame(jdf1,columns=['PL','Category','Q3 (May-Jul)'])

In [483]:
#fpromo['sku']=fpromo['Category']
fpromo.rename(columns= {'Category':'sku'},inplace=True )

In [484]:
fpromo

                     PL      sku  Q3 (May-Jul)
483   DELL8L_PC_Desktop  8L4A4QB        0.0000
17    DELL7Y_PC_Desktop  7Y4T6QB        0.0000
453   DELL0R_PC_Desktop  0R043QB        0.0000
30      HP38_PC_Desktop  385Z7PA        0.0000
900     HP9T_PC_Desktop  9T680PA        0.0000
...                 ...      ...           ...
375      DELLDG_SUP_TON   DG513Y    12635.0525
673        HPCE_SUP_TON   CE320A      995.8095
971        HPJ3_SUP_UNK   J3M70A        0.0000
1205       HP6Z_SUP_UNK  6ZD61AA        0.0000
522      DELLM1_SUP_UNK  M1T17BB        0.0000

[100 rows x 3 columns]

In [485]:
fpromo['season']='Jul'

In [486]:
fpromo.rename(columns= {'Q3 (May-Jul)':'promotion'},inplace=True )

In [487]:
fpromo.reset_index(drop=True)

                   PL      sku   promotion season
0   DELL8L_PC_Desktop  8L4A4QB      0.0000    Jul
1   DELL7Y_PC_Desktop  7Y4T6QB      0.0000    Jul
2   DELL0R_PC_Desktop  0R043QB      0.0000    Jul
3     HP38_PC_Desktop  385Z7PA      0.0000    Jul
4     HP9T_PC_Desktop  9T680PA      0.0000    Jul
..                ...      ...         ...    ...
95     DELLDG_SUP_TON   DG513Y  12635.0525    Jul
96       HPCE_SUP_TON   CE320A    995.8095    Jul
97       HPJ3_SUP_UNK   J3M70A      0.0000    Jul
98       HP6Z_SUP_UNK  6ZD61AA      0.0000    Jul
99     DELLM1_SUP_UNK  M1T17BB      0.0000    Jul

[100 rows x 4 columns]

In [489]:
fpromo[fpromo['promotion'] != 0].shape

(21, 4)